ci: Update to workflow to test publish action

diff --git a/.github/workflows/publish-website.yml b/.github/workflows/publish-website.yml
--- a/.github/workflows/publish-website.yml
+++ b/.github/workflows/publish-website.yml
@@ -4,17 +4,13 @@ run-name: Runs the site publish action for ${{ github.event.inputs.environment }
 on:
   workflow_dispatch:
     inputs:
-      site_id:
-        description: 'Insert Site ID'
-        default: '65cf252c355bb0ab87269e04'
-        required: true
-        type: string
-      domain:
+      site_label:
         type: choice
-        description:  Select which domain to publish
+        description: 'Select which site to publish'
         options:
-        - 65fad28eed7a6248275d2fe7
-        - some-other-domain.webflow.io
+        - webflow-copy.deriv.com
+        - pretend-site.webflow.io
+        required: true
 
 jobs:
   publish:
@@ -22,13 +18,24 @@ jobs:
 
     steps:
     - name: Checkout code
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
+    
+    - name: Map site label to site ID
+      id: map-site-id
+      run: |
+        echo "Mapping site label to site ID"
+        case "${{ github.event.inputs.site_label }}" in
+          "webflow-copy.deriv.com") SITE_ID="65cf252c355bb0ab87269e04" ;;
+          "pretend-site.webflow.io") SITE_ID="I_HAVE_NO_SITE_ID" ;;
+          *) echo "Invalid site label"; exit 1 ;;
+        esac
+        echo "::set-output name=site_id::$SITE_ID"
 
     - name: Trigger Webflow Publish
       env:
         WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
-        SITE_TO_DEPLOY: ${{ github.event.inputs.domain }}
-        SITE_ID: ${{ github.event.inputs.site_id }}
+        SITE_TO_DEPLOY: ${{ steps.map-site-id.outputs.site_id }}
+        SITE_ID: "65cf252c355bb0ab87269e04"
       run: |
         curl -X POST "https://api.webflow.com/v2/sites/$SITE_ID/publish" \
         -H "Authorization: Bearer $WEBFLOW_API_TOKEN" \
